### ISSUE TITLE
Torneos no se bloquean

### ISSUE THREAD

**Issue by Dres90** [calimat32/tourngen#1]
Despues de crear un torneo e incluso ingresar resultados todavia puedo generar partidos manualmente o incluso generar partidos automaticamente. No se muestran los partidos anteriores pero al generar la tabla de posiciones se nota que los partidos anteriormente creados siguen existentes

**Comment by calimat32** [comment]
Aún falta buscar la forma de bloquear el torneo en la base de datos... Puede tardar
