### ISSUE TITLE
Resultados de partidos

### ISSUE THREAD

**Issue by Dres90** [calimat32/tourngen#2]
Una vez modificado el resultado de un partido, aparece una confirmación. En este punto la unica manera de continuar es poner back en el browser. Si hago esto, el partido que modifiqué desaparece de la lista.
Además puedo poner goles negativos

**Comment by calimat32** [comment]
Se supone que el partido debe desaparecer, lo que hace falta es un mensaje de confirmación para saber si es que quiere continuar con este método. Los goles negativos puedo modificarlo dentro de esta semana.

**Comment by calimat32** [comment]
chch
